import assert from "node:assert/strict";
import test from "node:test";
import { createServer } from "node:http";
import sharp from "sharp";
import { companions } from "../dist/observation/companions.js";
import { addVideoArtifact, removeVideoArtifact } from "../dist/observation/artifacts.js";
import { VideoWriter } from "../dist/observation/video.js";

test("real HTTP companion routes enforce upload scopes, origin, replay and agent-only video downloads", async t => {
  process.env.ROBLOX_MCP_AUTH_TOKEN = "test-only-agent-credential";
  process.env.ROBLOX_MCP_CONNECTOR_TOKEN = "test-only-connector-credential";
  const { loadRoutes, dispatchHttp } = await import("../dist/http/router.js"); await loadRoutes();
  const server = createServer(dispatchHttp); await new Promise(resolve => server.listen(0, "127.0.0.1", resolve));
  t.after(async () => { companions.close("http-test"); removeVideoArtifact("http-test"); await new Promise(resolve => server.close(resolve)); });
  const base = `http://127.0.0.1:${server.address().port}`;
  const post = (route, data, token, origin) => fetch(base + route, { method: "POST", headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(origin ? { Origin: origin } : {}) }, body: JSON.stringify(data) });
  const pairing = companions.create("http-test", { kind: "capture", clientId: "test", sessionId: "session" });
  const claim = { pairingCode: pairing.pairingCode, label: "http-fixture", bootId: "boot", deviceUnixMs: Date.now() };
  assert.equal((await post("/companion/claim", claim, undefined, "https://unrelated.invalid")).status, 403);
  const response = await post("/companion/claim", claim); assert.equal(response.status, 200); const credential = await response.json();
  assert.equal((await post("/companion/claim", claim)).status, 403);
  const image = await sharp({ create: { width: 320, height: 180, channels: 3, background: "white" } }).jpeg().toBuffer();
  const frame = { sequence: 1, ptsMs: 0, capturedAtUnixMs: Date.now(), backend: "android-mediaprojection", imageBase64: image.toString("base64") };
  assert.equal((await post("/companion/frame", frame)).status, 403);
  assert.equal((await post("/companion/frame", frame, process.env.ROBLOX_MCP_CONNECTOR_TOKEN)).status, 403);
  assert.equal((await post("/companion/frame", frame, credential.uploadToken)).status, 200);
  assert.equal((await post("/companion/frame", frame, credential.uploadToken)).status, 422);
  assert.equal((await post("/companion/telemetry", {}, credential.uploadToken)).status, 403);
  assert.equal((await fetch(base + "/api/status", { headers: { Authorization: `Bearer ${credential.uploadToken}` } })).status, 403);
  const project = companions.create("http-test", { kind: "server", placeId: "123" });
  const projectClaim = await (await post("/companion/claim", { ...claim, pairingCode: project.pairingCode })).json();
  const batch = { sequence: 1, capturedAtUnixMs: Date.now(), placeId: "123", jobId: "studio-test", events: [{ kind: "event", name: "ready", atUnixMs: Date.now(), data: { ready: true } }] };
  assert.equal((await post("/companion/telemetry", batch, projectClaim.uploadToken)).status, 200);
  assert.equal((await post("/companion/telemetry", { ...batch, sequence: 2, placeId: "456" }, projectClaim.uploadToken)).status, 422);
  const writer = new VideoWriter(); t.after(() => writer.release()); await writer.append(image, 0, Date.now());
  const video = await writer.finish(); addVideoArtifact("http-test", "http-test-artifact", video.file);
  const download = base + "/api/recording-video?id=http-test-artifact";
  assert.equal((await fetch(download)).status, 403);
  assert.equal((await fetch(download, { headers: { Authorization: `Bearer ${credential.uploadToken}` } })).status, 403);
  const chunk = await fetch(download, { headers: { Authorization: `Bearer ${process.env.ROBLOX_MCP_AUTH_TOKEN}`, Range: "bytes=0-31" } });
  assert.equal(chunk.status, 206); assert.equal((await chunk.arrayBuffer()).byteLength, 32);
  const invalid = await fetch(download, { headers: { Authorization: `Bearer ${process.env.ROBLOX_MCP_AUTH_TOKEN}`, Range: "bytes=999999999-" } }); assert.equal(invalid.status, 416);
  companions.revoke("http-test", pairing.companionId);
  assert.equal((await post("/companion/frame", { ...frame, sequence: 2, ptsMs: 200 }, credential.uploadToken)).status, 403);
});
